version: "3.7"
services:
  api_server:
    build:
      context: .
      target: server
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      - MONGO_DOCKER_HOST=mongo:27017
    depends_on:
      - mongo
    command: npm start
    networks:
      - app-network
  mongo:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge